import type { Book } from "./books.types";

export const books: Book[] = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 12.99,
    originalPrice: 18.99,
    rating: 4.5,
    reviewCount: 2847,
    category: "Fiction",
    cover: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
    description: "The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, set in the roaring twenties.",
    isbn: "978-0743273565",
    pages: 180,
    publishedDate: "1925-04-10",
    inStock: true,
    bestseller: true,
    tags: ["classic", "american literature", "romance"],
  },
  {
    id: "2",
    title: "1984",
    author: "George Orwell",
    price: 14.99,
    originalPrice: 19.99,
    rating: 4.7,
    reviewCount: 5213,
    category: "Sci-Fi",
    cover: "https://images.unsplash.com/photo-1535905557558-afc4877a26fc?w=400&h=600&fit=crop",
    description: "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism, mass surveillance, and repressive regimentation.",
    isbn: "978-0451524935",
    pages: 328,
    publishedDate: "1949-06-08",
    inStock: true,
    bestseller: true,
    tags: ["dystopian", "political", "classic"],
  },
  {
    id: "3",
    title: "Clean Code",
    author: "Robert C. Martin",
    price: 42.99,
    originalPrice: 54.99,
    rating: 4.6,
    reviewCount: 1892,
    category: "Tech",
    cover: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400&h=600&fit=crop",
    description: "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees. This book is a must for any developer.",
    isbn: "978-0132350884",
    pages: 464,
    publishedDate: "2008-08-01",
    inStock: true,
    bestseller: true,
    tags: ["programming", "software engineering", "best practices"],
  },
  {
    id: "4",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    price: 16.99,
    rating: 4.3,
    reviewCount: 3421,
    category: "Mystery",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop",
    description: "Alicia Berenson's life is seemingly perfect. Then she shoots her husband five times in the face and then never speaks another word.",
    isbn: "978-1250301697",
    pages: 336,
    publishedDate: "2019-02-05",
    inStock: true,
    bestseller: true,
    tags: ["thriller", "psychological", "suspense"],
  },
  {
    id: "5",
    title: "Atomic Habits",
    author: "James Clear",
    price: 21.99,
    originalPrice: 27.99,
    rating: 4.8,
    reviewCount: 8934,
    category: "Non-Fiction",
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop",
    description: "No matter your goals, Atomic Habits offers a proven framework for improving--every day.",
    isbn: "978-0735211292",
    pages: 320,
    publishedDate: "2018-10-16",
    inStock: true,
    bestseller: true,
    tags: ["self-help", "productivity", "psychology"],
  },
  {
    id: "6",
    title: "Project Hail Mary",
    author: "Andy Weir",
    price: 24.99,
    originalPrice: 29.99,
    rating: 4.9,
    reviewCount: 4521,
    category: "Sci-Fi",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=600&fit=crop",
    description: "Ryland Grace is the sole survivor on a desperate, last-chance mission--and if he fails, humanity and the earth itself will perish.",
    isbn: "978-0593135204",
    pages: 496,
    publishedDate: "2021-05-04",
    inStock: true,
    bestseller: true,
    tags: ["space", "science", "adventure"],
  },
  {
    id: "7",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 9.99,
    originalPrice: 14.99,
    rating: 4.6,
    reviewCount: 6721,
    category: "Romance",
    cover: "https://images.unsplash.com/photo-1474932430478-367dbb6832c1?w=400&h=600&fit=crop",
    description: "The romantic clash between the opinionated Elizabeth Bennet and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring.",
    isbn: "978-0141439518",
    pages: 432,
    publishedDate: "1813-01-28",
    inStock: true,
    tags: ["classic", "romance", "british literature"],
  },
  {
    id: "8",
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt & David Thomas",
    price: 49.99,
    originalPrice: 59.99,
    rating: 4.7,
    reviewCount: 1234,
    category: "Tech",
    cover: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=600&fit=crop",
    description: "This book cuts through the increasing specialization and technicalities of modern software development to examine the core process.",
    isbn: "978-0201616224",
    pages: 352,
    publishedDate: "1999-10-20",
    inStock: true,
    tags: ["programming", "career", "software development"],
  },
  {
    id: "9",
    title: "Gone Girl",
    author: "Gillian Flynn",
    price: 15.99,
    originalPrice: 19.99,
    rating: 4.2,
    reviewCount: 5632,
    category: "Mystery",
    cover: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=400&h=600&fit=crop",
    description: "On the morning of his fifth wedding anniversary, Nick Dunne's wife Amy suddenly disappears. The police suspect Nick.",
    isbn: "978-0307588371",
    pages: 432,
    publishedDate: "2012-06-05",
    inStock: true,
    tags: ["thriller", "psychological", "domestic"],
  },
  {
    id: "10",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: 22.99,
    originalPrice: 28.99,
    rating: 4.5,
    reviewCount: 7891,
    category: "Non-Fiction",
    cover: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=600&fit=crop",
    description: "From a renowned historian comes a groundbreaking narrative of humanity's creation and evolution.",
    isbn: "978-0062316097",
    pages: 443,
    publishedDate: "2011-01-01",
    inStock: true,
    bestseller: true,
    tags: ["history", "anthropology", "science"],
  },
  {
    id: "11",
    title: "Dune",
    author: "Frank Herbert",
    price: 18.99,
    originalPrice: 24.99,
    rating: 4.7,
    reviewCount: 6789,
    category: "Sci-Fi",
    cover: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400&h=600&fit=crop",
    description: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.",
    isbn: "978-0441013593",
    pages: 896,
    publishedDate: "1965-08-01",
    inStock: true,
    bestseller: true,
    tags: ["space opera", "classic", "epic"],
  },
  {
    id: "12",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 11.99,
    originalPrice: 16.99,
    rating: 4.8,
    reviewCount: 9234,
    category: "Fiction",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop",
    description: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.",
    isbn: "978-0061120084",
    pages: 336,
    publishedDate: "1960-07-11",
    inStock: true,
    bestseller: true,
    tags: ["classic", "american literature", "coming of age"],
  },
  {
    id: "13",
    title: "The Notebook",
    author: "Nicholas Sparks",
    price: 13.99,
    rating: 4.1,
    reviewCount: 3456,
    category: "Romance",
    cover: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400&h=600&fit=crop",
    description: "Every so often a love story so captures our hearts that it becomes more than a story--it becomes an experience to remember forever.",
    isbn: "978-0446520802",
    pages: 214,
    publishedDate: "1996-10-01",
    inStock: true,
    tags: ["romance", "contemporary", "emotional"],
  },
  {
    id: "14",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    price: 55.99,
    originalPrice: 69.99,
    rating: 4.9,
    reviewCount: 876,
    category: "Tech",
    cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=600&fit=crop",
    description: "This book examines the architecture of data-intensive applications and the fundamental ideas behind them.",
    isbn: "978-1449373320",
    pages: 616,
    publishedDate: "2017-03-16",
    inStock: true,
    tags: ["database", "distributed systems", "architecture"],
  },
  {
    id: "15",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    price: 17.99,
    originalPrice: 22.99,
    rating: 4.0,
    reviewCount: 7890,
    category: "Mystery",
    cover: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400&h=600&fit=crop",
    description: "While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night.",
    isbn: "978-0307474278",
    pages: 489,
    publishedDate: "2003-03-18",
    inStock: true,
    tags: ["thriller", "conspiracy", "art history"],
  },
  {
    id: "16",
    title: "Educated",
    author: "Tara Westover",
    price: 19.99,
    originalPrice: 26.99,
    rating: 4.6,
    reviewCount: 5432,
    category: "Non-Fiction",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&h=600&fit=crop",
    description: "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom.",
    isbn: "978-0399590504",
    pages: 352,
    publishedDate: "2018-02-20",
    inStock: true,
    bestseller: true,
    tags: ["memoir", "education", "family"],
  },
];

export function getBookById(id: string): Book | undefined {
  return books.find((book) => book.id === id);
}

export function getBooksByCategory(category: string): Book[] {
  if (category === "All") return books;
  return books.filter((book) => book.category === category);
}

export function searchBooks(query: string): Book[] {
  const lower = query.toLowerCase();
  return books.filter(
    (book) =>
      book.title.toLowerCase().includes(lower) ||
      book.author.toLowerCase().includes(lower) ||
      book.isbn.includes(query) ||
      book.tags.some((tag) => tag.toLowerCase().includes(lower))
  );
}

export function sortBooks(books: Book[], sort: string): Book[] {
  const sorted = [...books];
  switch (sort) {
    case "price-low":
      return sorted.sort((a, b) => a.price - b.price);
    case "price-high":
      return sorted.sort((a, b) => b.price - a.price);
    case "rating":
      return sorted.sort((a, b) => b.rating - a.rating);
    case "newest":
      return sorted.sort(
        (a, b) =>
          new Date(b.publishedDate).getTime() - new Date(a.publishedDate).getTime()
      );
    default:
      return sorted;
  }
}

export function getBestsellers(limit: number = 6): Book[] {
  return books.filter((b) => b.bestseller).slice(0, limit);
}
